// <auto-generated />
using System;
using BlazorCashRegister.Data.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BlazorCashRegister.Data.Migrations
{
    [DbContext(typeof(CashRegisterContext))]
    partial class CashRegisterContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BlazorCashRegister.Data.Entities.Models.Article", b =>
                {
                    b.Property<int>("ArticleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<Guid>("Barcode")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsTaxRateReduced")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("UnitsInStock")
                        .HasColumnType("int");

                    b.HasKey("ArticleId");

                    b.ToTable("Articles");
                });

            modelBuilder.Entity("BlazorCashRegister.Data.Entities.Models.ArticleReceipt", b =>
                {
                    b.Property<int>("ArticleId")
                        .HasColumnType("int");

                    b.Property<int>("ReceiptId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("ArticleId", "ReceiptId");

                    b.HasIndex("ReceiptId");

                    b.ToTable("ArticleReceipts");
                });

            modelBuilder.Entity("BlazorCashRegister.Data.Entities.Models.CashRegister", b =>
                {
                    b.Property<int>("CashRegisterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("CashRegisterId");

                    b.ToTable("CashRegisters");
                });

            modelBuilder.Entity("BlazorCashRegister.Data.Entities.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Token")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmployeeId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("BlazorCashRegister.Data.Entities.Models.Receipt", b =>
                {
                    b.Property<int>("ReceiptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int?>("RegisterCashRegisterId")
                        .HasColumnType("int");

                    b.Property<Guid>("SerialNumber")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.HasKey("ReceiptId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("RegisterCashRegisterId");

                    b.ToTable("Receipts");
                });

            modelBuilder.Entity("BlazorCashRegister.Data.Entities.Models.ArticleReceipt", b =>
                {
                    b.HasOne("BlazorCashRegister.Data.Entities.Models.Article", "Article")
                        .WithMany("ArticleReceipts")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlazorCashRegister.Data.Entities.Models.Receipt", "Receipt")
                        .WithMany("ArticleReceipts")
                        .HasForeignKey("ReceiptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");

                    b.Navigation("Receipt");
                });

            modelBuilder.Entity("BlazorCashRegister.Data.Entities.Models.Receipt", b =>
                {
                    b.HasOne("BlazorCashRegister.Data.Entities.Models.Employee", "Employee")
                        .WithMany("Receipts")
                        .HasForeignKey("EmployeeId");

                    b.HasOne("BlazorCashRegister.Data.Entities.Models.CashRegister", "Register")
                        .WithMany("Receipts")
                        .HasForeignKey("RegisterCashRegisterId");

                    b.Navigation("Employee");

                    b.Navigation("Register");
                });

            modelBuilder.Entity("BlazorCashRegister.Data.Entities.Models.Article", b =>
                {
                    b.Navigation("ArticleReceipts");
                });

            modelBuilder.Entity("BlazorCashRegister.Data.Entities.Models.CashRegister", b =>
                {
                    b.Navigation("Receipts");
                });

            modelBuilder.Entity("BlazorCashRegister.Data.Entities.Models.Employee", b =>
                {
                    b.Navigation("Receipts");
                });

            modelBuilder.Entity("BlazorCashRegister.Data.Entities.Models.Receipt", b =>
                {
                    b.Navigation("ArticleReceipts");
                });
#pragma warning restore 612, 618
        }
    }
}
